# Problem Statement : 

# Given above data build a machine learning model that can predict Salary of Employee based on Test Score and Experience

In [1]:
import pandas as pd # for data frame
import numpy as np # for mathemetical operation
import matplotlib.pyplot as plt # for vizualization
%matplotlib inline
from sklearn import linear_model  #  For regression in Machine Learning
from sklearn.metrics import r2_score,mean_squared_error # For Accuracy

In [2]:
#loading dataset

df = pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [8]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
# Convert numeric words to numbers
# Using word2number

In [4]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [5]:
from word2number import w2n

In [10]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [13]:
import math
median_test_score  = math.floor(df["test_score(out of 10)"].median())
median_test_score

8

In [15]:
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [19]:
#split independent and dependent variables
X = df.iloc[:,:-1]
X

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    8.0                           7
7          11                    7.0                           8

In [20]:
Y = df["salary($)"]

In [23]:
#create linear regression model

reg = linear_model.LinearRegression()
reg.fit(X.values,Y)

LinearRegression()

In [24]:
#predict salary for given dataset

salary_predicted=reg.predict(X.values)
salary_predicted

array([52350.0727802 , 45734.35225619, 58312.95487627, 63872.63464338,
       67270.74235808, 61148.47161572, 76069.1411936 , 79241.63027656])

In [25]:
mse = mean_squared_error(df["salary($)"],salary_predicted)
print('MSE : ',mse)

MSE :  4435771.47016012


In [26]:
r2=r2_score(df["salary($)"],salary_predicted)
print('R2 score : ', r2)

R2 score :  0.9616780002577959


### Y = m1*X1  + m2*X2 + m3*X3 + c

In [30]:
c = reg.intercept_ 
print("c : ",c)

c :  17737.26346433771


In [34]:
m = reg.coef_

In [36]:
m1,m2,m3 = m[0],m[1],m[2]

In [37]:
#predict salary with 2 years of experiene, 9 test score and 6 interview score

In [38]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [42]:
m1*2 + m2*9 + m3*6 + c

53205.96797671034

In [39]:
#predict salary with 12 years of experiene, 10 test score and 10 interview score

In [40]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [43]:
m1*12 + m2*10 + m3*10 + c

92002.18340611353